# based on https://github.com/cypress-io/cypress-example-kitchensink/blob/aaca09645cb55716a8359ccb36b3661747c69ccd/basic/.travis.yml
language: node_js

node_js:
  - '10.15'

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn bootstrap

script:
  # for debugging
  - ls -lha node_modules/storybook-addon-data
  # actual tests
  - yarn build
  - yarn start-test-server
  # after all tests finish running we need to kill all background jobs
  # (like "npm start &")
  - kill $(jobs -p) || true

cache:
  yarn: true
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy-verify
